name: eks-deploy

on:
  push:
    branches: [ main ]
    paths: .github/workflows/eks-deploy.yml
  pull_request:
    branches:  none # [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  CLUSTER_NAME: efuse-eks-cluster
  
jobs:

  deploy-eks:
    runs-on: ubuntu-latest
    steps:

    - name: Git Checkout
      uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.26.1'
      id: install  
  
    - name: Configure AWS credentials from AWS account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}
        aws-region: ${{ secrets.AWS_REGION }}
        role-session-name: GitHub-OIDC-EKS 
        cluster-name: ${{ env.CLUSTER_NAME }}  

    - name: Deploy  to Amazon EKS
      run: |
        kubectl apply -f k8s/nginx.yaml
        kubectl apply -f k8s/whoami.yaml